version: "2.2"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Added quotes
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    depends_on:
      - mysqldb
    image: wiemtrifi/devopsproject:1.0.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 6868:8082
    stdin_open: true
    tty: true

volumes:
  db: